queue_rules:
  - name: default
    queue_conditions:
      - author=dependabot[bot]
      - check-success=Build
    update_method: merge
    merge_conditions:
      - author=dependabot[bot]
      - check-success=Build
    commit_message_template: |-
      {{ title }} (#{{ number }})
      {{ body }}
    merge_method: squash
    batch_size: 1

pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions: []
    actions:
      queue:
